services:
    auth:
        build: "./auth"
        ports:
            - 3003:3003
        env_file:
            - "./auth/.env"
        networks:
            - axon-network

    workspace:
        build: "./workspace"
        ports:
            - 3002:3002
        env_file:
            - "./workspace/.env"
        networks:
            - axon-network

    blog:
        build: "./blog"
        ports:
            - 3008:3008
        env_file:
            - "./blog/.env"
        networks:
            - axon-network
        
    gateway:
        build: "./gateway"
        ports:
            - 3001:3001
        networks:
            - axon-network
        depends_on:
            - auth
            - workspace
            - blog

networks:
    axon-network:
        driver: bridge
