import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Inter } from "next/font/google";

const open_Sans = Open_Sans({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
	display: "swap",
});

const inter = Inter({
	weight: ["300", "400", "500", "600", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} text-white bg-customMain flex`}>
				{children}
			</body>
		</html>
	);
}
